name: textomize
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
#  syncfusion_flutter_pdfviewer: ^24.1.41
  syncfusion_flutter_pdfviewer: ^29.1.41
  cupertino_icons: ^1.0.8
  svg_flutter: ^0.0.1
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.16
  smooth_page_indicator: ^1.2.0+3
  flutter_spinkit: ^5.2.1
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  flutter_staggered_grid_view: ^0.7.0
  camera: ^0.11.0+2
  path_provider: ^2.1.5
  shared_preferences: ^2.5.1
  curved_navigation_bar: ^1.0.6
  file_picker: ^9.0.0
  image_cropper: 9.0.0
  google_mlkit_text_recognition: ^0.13.0
  translator: ^1.0.3+1
  google_ml_kit: ^0.18.1
  share_plus: ^10.1.4
  salomon_bottom_bar: ^3.3.2
  permission_handler: ^12.0.0+1
  pdf: ^3.11.3
  docx_template: ^0.4.0
  open_file: ^3.3.2
  dotted_border: ^2.1.0
  intl: ^0.20.2
  lucide_icons: ^0.257.0
  excel: ^4.0.6
  fluttertoast: ^8.2.12
  provider: ^6.0.5
  printing: ^5.9.1
  firebase_core: ^3.13.0
  media_scanner: 2.2.0

  # firebase_storage: ^11.1.0
  # firebase_messaging: ^14.5.0
  # firebase_dynamic_links: ^5.0.0

  cloud_firestore: ^5.6.7
  firebase_auth: ^5.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svg/
    - assets/png/
    - assets/template.docx
    - assets/png/LogoWhite.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
    - family: BalsamiqSans
      fonts:
        - asset: assets/fonts/BalsamiqSans-Regular.ttf
        - asset: assets/fonts/BalsamiqSans-Bold.ttf
