// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4CFC6lE_Jw4wx8BwlzXk59NhDSDbwSPI',
    appId: '1:152447606859:web:eb9eb3960bde132936edce',
    messagingSenderId: '152447606859',
    projectId: 'textomize',
    authDomain: 'textomize.firebaseapp.com',
    storageBucket: 'textomize.firebasestorage.app',
    measurementId: 'G-PR58415FR9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqCJhMHlKm259fQzNHP7liCDTL7j6usiw',
    appId: '1:152447606859:android:0e4928461356e64936edce',
    messagingSenderId: '152447606859',
    projectId: 'textomize',
    storageBucket: 'textomize.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9ba0vvgu0eaDS3n8XkrbvMVE4kMgwHh8',
    appId: '1:152447606859:ios:7d70314b9e3c267136edce',
    messagingSenderId: '152447606859',
    projectId: 'textomize',
    storageBucket: 'textomize.firebasestorage.app',
    iosBundleId: 'com.example.textomize',
  );
}
